CREATE TABLE user (
	id VARCHAR NOT NULL PRIMARY KEY,
	username VARCHAR(36) NOT NULL UNIQUE,
	email VARCHAR(72) NOT NULL UNIQUE,
	password VARCHAR(36) NOT NULL,
	token VARCHAR(36) NOT NULL,
	verification_code VARCHAR(36) UNIQUE DEFAULT NULL,
	is_verified BOOLEAN NOT NULL DEFAULT 0,
	is_admin BOOLEAN NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);