CREATE TABLE user (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	username VARCHAR(32) NOT NULL UNIQUE,
	email VARCHAR(64) NOT NULL UNIQUE,
	password VARCHAR(32) NOT NULL,
	token VARCHAR(32) NOT NULL,
	verification_code VARCHAR(32) UNIQUE DEFAULT NULL,
	verified BOOLEAN NOT NULL DEFAULT 0,
	is_admin BOOLEAN NOT NULL DEFAULT 0
);