CREATE TABLE module_version (
	id VARCHAR(36) PRIMARY KEY,
	version VARCHAR(36) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	module VARCHAR(36) NOT NULL,
	publisher VARCHAR(36) NOT NULL,
	FOREIGN KEY (module) REFERENCES module(id),
	FOREIGN KEY (publisher) REFERENCES user(id) ON DELETE CASCADE
);